var
   A, B, resultado: inteiro

inicio
   // Ler os dois valores inteiros
   escreva("Digite o valor de A: ")
   leia(A)

   escreva("Digite o valor de B: ")
   leia(B)

   // Calcular o quadrado da diferença entre A e B
   resultado := (A - B) * (A - B)

   // Apresentar o resultado
   escrevaL("O quadrado da diferença de A por B é: ", resultado)

fimalgoritmo
By:Gustavo Santana